// Generated by CoffeeScript 1.11.1
(function() {
  var Qiita;

  Qiita = require('../kitchen/qiita');

  Qiita.setToken = function(token) {
    return Qiita._token = token;
  };

  Qiita.setEndpoint = function(endpoint) {
    return Qiita._endpoint = endpoint;
  };

  Qiita.setRequester(function(method, api, params) {
    var _endpoint, _token, fetching, k, query, url, v;
    _token = Qiita._token, _endpoint = Qiita._endpoint;
    url = _endpoint + api;
    fetching = method === 'GET' ? (query = ((function() {
      var results;
      results = [];
      for (k in params) {
        v = params[k];
        results.push(k + '=' + v);
      }
      return results;
    })()).join('&'), fetch(url + "?" + query, {
      method: 'GET',
      headers: {
        Authorization: 'Bearer ' + _token,
        'Content-Type': 'application/json',
        Accept: 'application/json'
      }
    })) : (url = _endpoint + api, fetch(url, {
      method: method,
      headers: {
        Authorization: 'Bearer ' + _token,
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(params)
    }));
    return fetching.then(function(res) {
      var error;
      if (parseInt(res.status, 10) >= 400) {
        error = new Error('qiita-js request error:' + method + ' ' + url + ' ' + JSON.stringify(params) + '' + '\n' + res.body.error);
        return Promise.reject(error);
      }
      return res;
    });
  });

  module.exports = Qiita;

}).call(this);
